### ISSUE TITLE
[question] how to build this?

### ISSUE THREAD

**Issue by Airblader** [Zubnix/xcb4j#4]
Hi,

as per your request I'll post this on here. Would you mind explaining how I can build this project? I've tried `make` with the Makefile, but that just gives me

```
make: *** No rule to make target '../../../target/generated-sources/swig/org/freedesktop/xcb/xcbJNI.c', needed by 'xcbJNI.o'.  Stop.
```

Thanks in advance!

**Comment by Zubnix** [comment]
Have you tried building with maven? Run `mvn install` in the same directory as where the pom.xml file is located. The makefile is called by the maven build system after C source files have been generated by swig.

**Comment by Airblader** [comment]
D'oh. I totally didn't see the `pom.xml`. Sorry for the stupid question. I'll try to give this a shot as soon as possible. Thanks for your work!

**Comment by Zubnix** [comment]
you might have to run mvn install twice as there is a bug where resources are sometimes not properly included in the resulting jar.

**Comment by Airblader** [comment]
Alright. Thanks for the headsup :)
