### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by s5bug** [Zubnix/xcb4j#5]
New to this `xcb` thing, don't know what I'm supposed to do at all to get stuff on the screen. Figured out `LibXcbLoader.load()` but that's about it :sweat_smile:

**Comment by Zubnix** [comment]
xcb4j is just a mapping to libxcb to do raw X server communication. As such it's usage is the same as libxcb.

You can try porting 2. https://xcb.freedesktop.org/windowcontextandmanipulation/
to xcb4j and see where it gets you.

There's more info available if you google a bit. It does however expects a certain basic knowledge how the X11 protocol works. https://www.x.org/releases/X11R7.6/doc/libxcb/tutorial/index.html

**Comment by s5bug** [comment]
All of this is done with the `LibXcb` class correct? (Sorry for late response, just moved in to new house)

**Comment by Zubnix** [comment]
Only for function calls. Structs live as separate classes. See swig for details.
